### ISSUE TITLE
Looker API: Version-3x-deprecation

### ISSUE THREAD

**Issue by philipp-heinrich** [singer-io/tap-looker#10]
Hej. Looker deprecated their 3.x API. [>link](https://developers.looker.com/api/advanced-usage/version-3x-deprecation)
Are there any plans, to support their newest API version (4.0) in the near future?

**Comment by deanlooker** [comment]
Hi Stitch team,

Any update on this? The Looker API v3 and v3.1 will be removed from the product in the July 2023 Looker release and subsequent releases. Any calls to 3.0 or 3.1 endpoints will cease to work after that change, so any customers relying on this integration will run into severe problems if Stitch does not update their code by then. 

Dean Hicks
Developer Relations Engineer @ Looker

**Comment by deanlooker** [comment]
@leslievandemark tagging since I see you're the most recent contributor.

https://cloud.google.com/looker/developers/api-deprecation

**Comment by alisa-aylward-toast** [comment]
hi all -- following up on this. any plans for this or should we plan to move off?

**Comment by rdeshmukh15** [comment]
@alisa-aylward-toast @deanlooker @philipp-heinrich : Upgraded tap-looker to latest version v4.0
